apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: 16.6.0
    helm:
      values: |
        auth:
          username: myuser
          password: mypassword
          database: mydb
        primary:
          persistence:
            enabled: true
            size: 5Gi
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true
              namespace: monitoring      
              interval: 30s   
  destination:
    server: https://kubernetes.default.svc
    namespace: postgresql
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
